apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  labels:
    app: cats
    owner: bhavin
spec:
  selector:
    matchLabels:
      app: cats
      owner: bhavin
  replicas: 3
  template:
    metadata:
      labels:
        app: cats
        owner: bhavin
    spec:
      containers:
      - name: cat
        image: 462033369097.dkr.ecr.us-east-1.amazonaws.com/cats-repo:v1.0
        ports:
        - containerPort: 80