apiVersion: v1
kind: Pod
metadata:
  name: cats #name of pods
  labels:
    app: cats
    owner: bhavin
spec:
  containers:
  - name: cat  #container name
    image: 462033369097.dkr.ecr.us-east-1.amazonaws.com/cats-repo:v1.0
    ports:
    - containerPort: 80
      hostPort: 8080