apiVersion: v1
kind: Service
metadata:
  name: catservice
  labels:
    app: cats
    owner: bhavin
spec:
  type: NodePort
  ports:
  - port: 80  #clusterIP port 
    targetPort: 80
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30000
  selector:
    app: cats